# Spring Properties
spring:
  application:
     name: cycling-stats
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/cycling-stats/templates/    # Trailing / mandatory
                       # Template location for this application only

# HTTP Server
server:
  port: 8888   # HTTP (Tomcat) port

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Connection details
connection:
  cookie: __cfduid=d3cd04ce6692ca5ffa7d0884a879ef3671502963235; PHPSESSID=tc07vh9jll5oa8mc07rhqlu9e3; _ga=GA1.2.1146337387.1502963237; _gid=GA1.2.569996841.1502963237; __gads=ID=527d3fb82a7f7d9b:T=1502963236:S=ALNI_MbHEPQzvbWDOzo9diHX9JHMFvXqmA; procyclingstats_cookie_consent=yes
  url: http://www.procyclingstats.com
  user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0